SET NAMES utf8mb4;
SET SQL_SAFE_UPDATES = 0;
SET sql_mode = '';
SET FOREIGN_KEY_CHECKS = 0;

-- Cambia la ruta del archivo CSV a CargaCredito.csv
SET @csv_file = 'c:/xampp/htdocs/Conta/temp/CargaCredito.csv';

-- 1) Staging (preserva toda la info del Excel)
DROP TABLE IF EXISTS stg_carga_credito;
CREATE TABLE stg_carga_credito (
  fecha_desembolso_raw VARCHAR(50),
  num_exp_raw VARCHAR(50),
  estado_civil VARCHAR(50),
  codigo_busqueda2 VARCHAR(255),
  vendedor VARCHAR(255),
  telefono VARCHAR(50),
  direccion VARCHAR(255),
  num_prestamo_raw VARCHAR(50),
  sexo VARCHAR(10),
  anio_piriosidad VARCHAR(20),
  primer_seg_nombre VARCHAR(255),
  nombre_cliente2 VARCHAR(255),
  primer_nombre VARCHAR(100),
  segundo_nombre VARCHAR(100),
  primer_apellido VARCHAR(100),
  segundo_apellido VARCHAR(100),
  ruta2 VARCHAR(100),
  piriosidad_mes VARCHAR(50),
  dia VARCHAR(50),
  periosidad_pagos VARCHAR(100),
  cuota_no_raw VARCHAR(50),
  dias_raw VARCHAR(50),
  monto_credito_saldo_raw VARCHAR(50),
  principal_raw VARCHAR(50),
  interes_devengado_raw VARCHAR(50),
  comision_desembolso_raw VARCHAR(50),
  monto_cuota_raw VARCHAR(50),
  fecha_raw VARCHAR(50),
  recibo_no VARCHAR(100),
  monto_usd_raw VARCHAR(50),
  principal_usd_raw VARCHAR(50),
  interes_usd_raw VARCHAR(50),
  saldo_usd_raw VARCHAR(50),
  comision_desembolso2_raw VARCHAR(50),
  mora_usd_raw VARCHAR(50),
  dias_mora_raw VARCHAR(50),
  dias_mora2_raw VARCHAR(50),
  tipo VARCHAR(50),
  serie VARCHAR(50),
  consecutivo VARCHAR(50),
  suma_principal_interes_mora_raw VARCHAR(50),
  resultado VARCHAR(50),
  mes_desembolso VARCHAR(50),
  rango VARCHAR(100),
  rango_mora VARCHAR(100),
  mes_pagado VARCHAR(50),
  anio_pagado VARCHAR(10),
  agrupacion_credito VARCHAR(100),
  rango2 VARCHAR(100),
  c VARCHAR(20),
  nivel VARCHAR(20),
  interes_raw VARCHAR(50),
  frecuencia_pago VARCHAR(50),
  id_modalidad_credito VARCHAR(50),
  id_sector_economico VARCHAR(50),
  id_municipio VARCHAR(100),
  id_sector_economico2 VARCHAR(50),
  categoria VARCHAR(100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2) Carga del CSV
LOAD DATA LOCAL INFILE 'C:/xampp/htdocs/Conta/temp/CargaCredito.csv'
INTO TABLE stg_carga_credito
FIELDS TERMINATED BY ';'
OPTIONALLY ENCLOSED BY '"'
ESCAPED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(
  fecha_desembolso_raw,
  num_exp_raw,
  estado_civil,
  codigo_busqueda2,
  vendedor,
  telefono,
  direccion,
  num_prestamo_raw,
  sexo,
  anio_piriosidad,
  primer_seg_nombre,
  nombre_cliente2,
  primer_nombre,
  segundo_nombre,
  primer_apellido,
  segundo_apellido,
  ruta2,
  piriosidad_mes,
  dia,
  periosidad_pagos,
  cuota_no_raw,
  dias_raw,
  monto_credito_saldo_raw,
  principal_raw,
  interes_devengado_raw,
  comision_desembolso_raw,
  monto_cuota_raw,
  fecha_raw,
  recibo_no,
  monto_usd_raw,
  principal_usd_raw,
  interes_usd_raw,
  saldo_usd_raw,
  comision_desembolso2_raw,
  mora_usd_raw,
  dias_mora_raw,
  dias_mora2_raw,
  tipo,
  serie,
  consecutivo,
  suma_principal_interes_mora_raw,
  resultado,
  mes_desembolso,
  rango,
  rango_mora,
  mes_pagado,
  anio_pagado,
  agrupacion_credito,
  rango2,
  c,
  nivel,
  interes_raw,
  frecuencia_pago,
  id_modalidad_credito,
  id_sector_economico,
  id_municipio,
  id_sector_economico2,
  categoria
);
