-- Migración idempotente: Añade columnas necesarias a `tb_solicitudes`
-- Úsala en desarrollo/producción con precaución. Respaldar la tabla antes de ejecutar.

-- Nota: `ADD COLUMN IF NOT EXISTS` requiere MySQL 8+. Si usas MySQL 5.7 u otra versión
-- que no soporte `IF NOT EXISTS`, elimina la cláusula `IF NOT EXISTS` y ejecuta el script
-- una sola vez, o aplica checks manuales previos.

START TRANSACTION;

ALTER TABLE `tb_solicitudes`
  ADD COLUMN IF NOT EXISTS `giro_negocio` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `monto_solicitado` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `plazo_meses` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `frecuencia` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tasa_interes` DECIMAL(6,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `cuota_estim_estimada` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `garantia` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `otros_ingresos_detalle` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ventas_promedio_diarios` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ventas_promedio_mensual` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `detalle_inventario` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ventas_dias_buenos` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ventas_dias_malos` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `cuentas_por_cobrar_amount` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `caja_amount` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `banco_amount` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `numero_empleados` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `otros_gastos` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `pago_alquiler` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `pago_trabajadores` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `energia` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `agua` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `internet` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `numero_dependientes` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `fecha_nacimiento` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `edad` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `nombre_conyuge` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ocupacion_conyuge` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `telefono_conyuge` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tiempo_residir_anios` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tiempo_residir_meses` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `condicion_vivienda` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `es_nuevo` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `es_renovacion` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `nombre_empresa` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `direccion_empresa` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `telefono_empresa` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `cargo_puesto` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tiempo_empleo_anios` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tiempo_empleo_meses` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tipo_contrato` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ingreso_mensual_neto` DECIMAL(14,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `deducciones` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `nombre_negocio` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `actividad_economica` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ubicacion_negocio` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `telefono_negocio` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tiempo_operacion_anios` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tiempo_operacion_meses` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `propiedad_negocio` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `promotor` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `fecha_recepcion` DATE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `observaciones` TEXT DEFAULT NULL;

-- Columnas adicionales detectadas en el formulario que no estaban en el script original
ALTER TABLE `tb_solicitudes`
  ADD COLUMN IF NOT EXISTS `comentarios` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `negocio_propio` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `negocio_antiguedad` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `matricula_permiso` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `cedula_vigente` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `ingreso_promedio_alto` DECIMAL(15,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ingreso_promedio_bajo` DECIMAL(15,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `otros_ingresos` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `otros_ingresos_docs` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `datos_personales` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `recibo_servicios` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `dni_conyuge` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `cuentas_por_cobrar` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `ahorros` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `inventario_disponible` TINYINT(1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `porcentaje_recuperacion` DECIMAL(7,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `gastos_fijos` DECIMAL(15,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `gastos_operativos` DECIMAL(15,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `margen_comercial` DECIMAL(7,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `investigacion_vecinos` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `referencias_personales` TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `barrio` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `municipio` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tipo_credito` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `tipo_solicitud` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `estado_civil` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `uso_credito` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `analista` INT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `estado_aprobacion` VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `fecha_solicitud` DATETIME DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `fuente_ingresos` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `telefono_trabajo` VARCHAR(50) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `salario_conyuge` DECIMAL(14,2) DEFAULT NULL;

COMMIT;

-- Instrucciones rápidas (PowerShell):
-- mysql -u <usuario> -p <basededatos> < "c:\xampp\htdocs\servicredit\sql\alter_tb_solicitudes_add_fields.sql"

-- Si tu servidor no soporta `IF NOT EXISTS`, y quieres un chequeo previo manual, puedes
-- ejecutar antes:
-- SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'tb_solicitudes';
-- y añadir sólo las columnas faltantes.
