-- ALTER idempotente para actualizar/escalar la tabla `teso_accounts`
-- Añade columnas faltantes y ajusta tipos/auto_increment si es necesario
-- Ejecutar desde phpMyAdmin o cliente mysql contra la BD del sistema

SELECT COUNT(*) INTO @id_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='id';
SELECT COUNT(*) INTO @id_ai FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='id' AND EXTRA LIKE '%auto_increment%';
SELECT COUNT(*) INTO @idx_id FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='id';

-- Three cases:
-- 1) id does not exist -> add id as AUTO_INCREMENT PRIMARY KEY
-- 2) id exists and already indexed -> simply MODIFY to AUTO_INCREMENT
-- 3) id exists but not indexed -> in a single ALTER add an index and set AUTO_INCREMENT
SET @sql = IF(@id_exists=0,
	'ALTER TABLE teso_accounts ADD COLUMN id INT NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST',
	IF(@id_ai=0,
		IF(@idx_id>0,
			'ALTER TABLE teso_accounts MODIFY id INT NOT NULL AUTO_INCREMENT',
			'ALTER TABLE teso_accounts MODIFY id INT NOT NULL, ADD INDEX idx_teso_accounts_id (id), MODIFY id INT NOT NULL AUTO_INCREMENT'
		),
		'SELECT "skip"'
	)
);
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- code VARCHAR(64)
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='code';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='code' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=64;
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN code VARCHAR(64) NULL', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN code VARCHAR(64) NULL','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- name VARCHAR(255) NOT NULL
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='name';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='name' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=255 AND IS_NULLABLE='NO';
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN name VARCHAR(255) NOT NULL', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN name VARCHAR(255) NOT NULL','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- type VARCHAR(50)
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='type';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='type' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=50;
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN type VARCHAR(50) NULL', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN type VARCHAR(50) NULL','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- bank_name VARCHAR(255)
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='bank_name';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='bank_name' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=255;
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN bank_name VARCHAR(255) NULL', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN bank_name VARCHAR(255) NULL','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- account_number VARCHAR(128)
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='account_number';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='account_number' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=128;
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN account_number VARCHAR(128) NULL', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN account_number VARCHAR(128) NULL','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- currency VARCHAR(10)
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='currency';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='currency' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=10;
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN currency VARCHAR(10) NULL', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN currency VARCHAR(10) NULL','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- currency_symbol VARCHAR(8)
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='currency_symbol';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='currency_symbol' AND DATA_TYPE='varchar' AND CHARACTER_MAXIMUM_LENGTH=8;
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN currency_symbol VARCHAR(8) NULL', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN currency_symbol VARCHAR(8) NULL','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- estado TINYINT(1) NOT NULL DEFAULT 1
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='estado';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='estado' AND DATA_TYPE='tinyint' AND COLUMN_DEFAULT='1' AND IS_NULLABLE='NO';
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN estado TINYINT(1) NOT NULL DEFAULT 1', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN estado TINYINT(1) NOT NULL DEFAULT 1','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
SELECT COUNT(*) INTO @col_exists FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='created_at';
SELECT COUNT(*) INTO @col_ok FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND COLUMN_NAME='created_at' AND DATA_TYPE='datetime' AND COLUMN_DEFAULT IS NOT NULL;
SET @sql = IF(@col_exists=0,'ALTER TABLE teso_accounts ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP', IF(@col_ok=0,'ALTER TABLE teso_accounts MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP','SELECT "skip"'));
PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- Índices recomendados (nombres explícitos)
SELECT COUNT(*) INTO @idx FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND INDEX_NAME='idx_teso_accounts_code';
SET @sql = IF(@idx=0,'ALTER TABLE teso_accounts ADD INDEX idx_teso_accounts_code (code)','SELECT "skip"'); PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;
SELECT COUNT(*) INTO @idx FROM INFORMATION_SCHEMA.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='teso_accounts' AND INDEX_NAME='idx_teso_accounts_type';
SET @sql = IF(@idx=0,'ALTER TABLE teso_accounts ADD INDEX idx_teso_accounts_type (type)','SELECT "skip"'); PREPARE stm FROM @sql; EXECUTE stm; DEALLOCATE PREPARE stm;

-- Fin
