-- Tabla para almacenar el Perfil Integral del Cliente
CREATE TABLE IF NOT EXISTS `tb_perfil_integral_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solicitud_id` INT NOT NULL,
  `segundo_nombre` VARCHAR(255) DEFAULT NULL,
  `nombre_conocido` VARCHAR(255) DEFAULT NULL,
  `nombre` VARCHAR(255) DEFAULT NULL,
  `primer_apellido` VARCHAR(255) DEFAULT NULL,
  `segundo_apellido` VARCHAR(255) DEFAULT NULL,
  `estado_civil` VARCHAR(50) DEFAULT NULL,
  `sexo` VARCHAR(10) DEFAULT NULL,
  `n_dependientes` INT DEFAULT NULL,
  `tipo_documento` VARCHAR(50) DEFAULT NULL,
  `numero_documento` VARCHAR(100) DEFAULT NULL,
  
  `fecha_emision_documento` DATE DEFAULT NULL,
  `fecha_vencimiento_documento` DATE DEFAULT NULL,
  `fecha_nacimiento` DATE DEFAULT NULL,
  `pais_nacimiento` VARCHAR(100) DEFAULT NULL,
  `pais_nacionalidad` VARCHAR(100) DEFAULT NULL,
  `otra_nacionalidad` VARCHAR(100) DEFAULT NULL,
  `pais_residencia` VARCHAR(100) DEFAULT NULL,
  `telefono` VARCHAR(50) DEFAULT NULL,
  `celular` VARCHAR(50) DEFAULT NULL,
  `codigo_area` VARCHAR(20) DEFAULT NULL,
  `fax` VARCHAR(50) DEFAULT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `direccion` VARCHAR(255) DEFAULT NULL,
  `departamento` VARCHAR(100) DEFAULT NULL,
  `municipio` VARCHAR(100) DEFAULT NULL,
  `ciudad` VARCHAR(100) DEFAULT NULL,
  `nivel_riesgo` VARCHAR(50) DEFAULT NULL,
  `tipo_ddc` VARCHAR(100) DEFAULT NULL,
  `fecha_perfil` DATE DEFAULT NULL,
  `en_su_propio_pais` TINYINT(1) DEFAULT 0,
  `es_funcionario_publico` TINYINT(1) DEFAULT 0,
  `cargo_funcionario` VARCHAR(255) DEFAULT NULL,
  `ocupacion` VARCHAR(150) DEFAULT NULL,
  `categoria_empleo` VARCHAR(100) DEFAULT NULL,
  `categoria_otro` VARCHAR(255) DEFAULT NULL,
  `profesion` VARCHAR(150) DEFAULT NULL,
  `nombre_centro_trabajo` VARCHAR(255) DEFAULT NULL,
  `direccion_centro_trabajo` VARCHAR(255) DEFAULT NULL,
  `telefono_centro_trabajo` VARCHAR(50) DEFAULT NULL,
  `fax_centro_trabajo` VARCHAR(50) DEFAULT NULL,
  `sitio_web_centro_trabajo` VARCHAR(255) DEFAULT NULL,
  `cobertura_negocio` VARCHAR(100) DEFAULT NULL,
  `zona_cobertura` VARCHAR(50) DEFAULT NULL,
  `descripcion_actividad` TEXT DEFAULT NULL,
  `empresa` VARCHAR(255) DEFAULT NULL,
  `ingreso_mensual` DECIMAL(14,2) DEFAULT NULL,
  `ingreso_mensual_usd` DECIMAL(14,2) DEFAULT NULL,
  `ingreso_mensual_cordobas` DECIMAL(14,2) DEFAULT NULL,
  `antiguedad_laboral` VARCHAR(50) DEFAULT NULL,
  `conyuge_nombre` VARCHAR(255) DEFAULT NULL,
  `conyuge_apellido` VARCHAR(255) DEFAULT NULL,
  `conyuge_direccion` VARCHAR(255) DEFAULT NULL,
  `conyuge_telefono` VARCHAR(50) DEFAULT NULL,
  `conyuge_celular` VARCHAR(50) DEFAULT NULL,
  `conyuge_email` VARCHAR(150) DEFAULT NULL,
  `conyuge_profesion` VARCHAR(150) DEFAULT NULL,
  `conyuge_ocupacion_actual` VARCHAR(150) DEFAULT NULL,
  `conyuge_nombre_centro_trabajo` VARCHAR(255) DEFAULT NULL,
  `conyuge_direccion_centro_trabajo` VARCHAR(255) DEFAULT NULL,
  `conyuge_email_centro_trabajo` VARCHAR(150) DEFAULT NULL,
  `conyuge_sitio_web` VARCHAR(255) DEFAULT NULL,
  `conyuge_telefono_centro_trabajo` VARCHAR(50) DEFAULT NULL,
  `conyuge_fax_centro_trabajo` VARCHAR(50) DEFAULT NULL,
  `conyuge_apartado_postal` VARCHAR(100) DEFAULT NULL,
  `conyuge_ingreso_usd` DECIMAL(14,2) DEFAULT NULL,
  `conyuge_ingreso_cordobas` DECIMAL(14,2) DEFAULT NULL,
  `documento_legal_1_tipo` VARCHAR(100) DEFAULT NULL,
  `documento_legal_1_numero` VARCHAR(100) DEFAULT NULL,
  `documento_legal_1_registro` VARCHAR(100) DEFAULT NULL,
  `documento_legal_1_fecha_emision` DATE DEFAULT NULL,
  `documento_legal_1_fecha_vencimiento` DATE DEFAULT NULL,
  `documento_legal_2_tipo` VARCHAR(100) DEFAULT NULL,
  `documento_legal_2_numero` VARCHAR(100) DEFAULT NULL,
  `documento_legal_2_registro` VARCHAR(100) DEFAULT NULL,
  `documento_legal_2_fecha_emision` DATE DEFAULT NULL,
  `documento_legal_2_fecha_vencimiento` DATE DEFAULT NULL,
  `documento_legal_1_pais_emision` VARCHAR(100) DEFAULT NULL,
  `documento_legal_2_pais_emision` VARCHAR(100) DEFAULT NULL,
  `origen_fondos` TEXT DEFAULT NULL,
  `tipo_relacion` VARCHAR(255) DEFAULT NULL,
  `proposito_relacion` TEXT DEFAULT NULL,
  `actividad_esperada` TEXT DEFAULT NULL,
  `actividad_esperada_json` TEXT DEFAULT NULL,
  `lugar_fecha` VARCHAR(255) DEFAULT NULL,
  `declaro_veracidad` TINYINT(1) DEFAULT 0,
  `otros` TEXT DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`solicitud_id`)
);
