-- Reporte de completitud: muestra cuántos registros tienen cada campo llenado
SELECT
  COUNT(*) AS total_registros,
  SUM(CASE WHEN TRIM(IFNULL(giro_negocio,'')) <> '' THEN 1 ELSE 0 END) AS giro_negocio_filled,
  SUM(CASE WHEN monto_solicitado IS NOT NULL THEN 1 ELSE 0 END) AS monto_solicitado_filled,
  SUM(CASE WHEN plazo_meses IS NOT NULL THEN 1 ELSE 0 END) AS plazo_meses_filled,
  SUM(CASE WHEN TRIM(IFNULL(frecuencia,'')) <> '' THEN 1 ELSE 0 END) AS frecuencia_filled,
  SUM(CASE WHEN tasa_interes IS NOT NULL THEN 1 ELSE 0 END) AS tasa_interes_filled,
  SUM(CASE WHEN cuota_estim_estimada IS NOT NULL THEN 1 ELSE 0 END) AS cuota_estim_estimada_filled,
  SUM(CASE WHEN TRIM(IFNULL(garantia,'')) <> '' THEN 1 ELSE 0 END) AS garantia_filled,
  SUM(CASE WHEN TRIM(IFNULL(otros_ingresos_detalle,'')) <> '' THEN 1 ELSE 0 END) AS otros_ingresos_detalle_filled,
  SUM(CASE WHEN ventas_promedio_diarios IS NOT NULL THEN 1 ELSE 0 END) AS ventas_promedio_diarios_filled,
  SUM(CASE WHEN ventas_promedio_mensual IS NOT NULL THEN 1 ELSE 0 END) AS ventas_promedio_mensual_filled,
  SUM(CASE WHEN ventas_dias_buenos IS NOT NULL THEN 1 ELSE 0 END) AS ventas_dias_buenos_filled,
  SUM(CASE WHEN ventas_dias_malos IS NOT NULL THEN 1 ELSE 0 END) AS ventas_dias_malos_filled,
  SUM(CASE WHEN TRIM(IFNULL(detalle_inventario,'')) <> '' THEN 1 ELSE 0 END) AS detalle_inventario_filled,
  SUM(CASE WHEN cuentas_por_cobrar_amount IS NOT NULL THEN 1 ELSE 0 END) AS cuentas_por_cobrar_amount_filled,
  SUM(CASE WHEN caja_amount IS NOT NULL THEN 1 ELSE 0 END) AS caja_amount_filled,
  SUM(CASE WHEN banco_amount IS NOT NULL THEN 1 ELSE 0 END) AS banco_amount_filled,
  SUM(CASE WHEN pago_alquiler IS NOT NULL THEN 1 ELSE 0 END) AS pago_alquiler_filled,
  SUM(CASE WHEN pago_trabajadores IS NOT NULL THEN 1 ELSE 0 END) AS pago_trabajadores_filled,
  SUM(CASE WHEN energia IS NOT NULL THEN 1 ELSE 0 END) AS energia_filled,
  SUM(CASE WHEN agua IS NOT NULL THEN 1 ELSE 0 END) AS agua_filled,
  SUM(CASE WHEN internet IS NOT NULL THEN 1 ELSE 0 END) AS internet_filled,
  SUM(CASE WHEN TRIM(IFNULL(promotor,'')) <> '' THEN 1 ELSE 0 END) AS promotor_filled,
  SUM(CASE WHEN fecha_recepcion IS NOT NULL THEN 1 ELSE 0 END) AS fecha_recepcion_filled,
  SUM(CASE WHEN TRIM(IFNULL(observaciones,'')) <> '' THEN 1 ELSE 0 END) AS observaciones_filled,
  SUM(CASE WHEN TRIM(IFNULL(nombre_conyuge,'')) <> '' THEN 1 ELSE 0 END) AS nombre_conyuge_filled,
  SUM(CASE WHEN TRIM(IFNULL(ocupacion_conyuge,'')) <> '' THEN 1 ELSE 0 END) AS ocupacion_conyuge_filled,
  SUM(CASE WHEN TRIM(IFNULL(telefono_conyuge,'')) <> '' THEN 1 ELSE 0 END) AS telefono_conyuge_filled,
  SUM(CASE WHEN numero_dependientes IS NOT NULL THEN 1 ELSE 0 END) AS numero_dependientes_filled,
  SUM(CASE WHEN fecha_nacimiento IS NOT NULL THEN 1 ELSE 0 END) AS fecha_nacimiento_filled,
  SUM(CASE WHEN edad IS NOT NULL THEN 1 ELSE 0 END) AS edad_filled,
  SUM(CASE WHEN TRIM(IFNULL(nombre_empresa,'')) <> '' THEN 1 ELSE 0 END) AS nombre_empresa_filled,
  SUM(CASE WHEN TRIM(IFNULL(direccion_empresa,'')) <> '' THEN 1 ELSE 0 END) AS direccion_empresa_filled,
  SUM(CASE WHEN TRIM(IFNULL(telefono_empresa,'')) <> '' THEN 1 ELSE 0 END) AS telefono_empresa_filled,
  SUM(CASE WHEN TRIM(IFNULL(cargo_puesto,'')) <> '' THEN 1 ELSE 0 END) AS cargo_puesto_filled,
  SUM(CASE WHEN ingreso_mensual_neto IS NOT NULL THEN 1 ELSE 0 END) AS ingreso_mensual_neto_filled,
  SUM(CASE WHEN TRIM(IFNULL(nombre_negocio,'')) <> '' THEN 1 ELSE 0 END) AS nombre_negocio_filled,
  SUM(CASE WHEN TRIM(IFNULL(actividad_economica,'')) <> '' THEN 1 ELSE 0 END) AS actividad_economica_filled,
  SUM(CASE WHEN TRIM(IFNULL(ubicacion_negocio,'')) <> '' THEN 1 ELSE 0 END) AS ubicacion_negocio_filled,
  SUM(CASE WHEN TRIM(IFNULL(telefono_negocio,'')) <> '' THEN 1 ELSE 0 END) AS telefono_negocio_filled,
  SUM(CASE WHEN numero_empleados IS NOT NULL THEN 1 ELSE 0 END) AS numero_empleados_filled,
  SUM(CASE WHEN TRIM(IFNULL(otros_gastos,'')) <> '' THEN 1 ELSE 0 END) AS otros_gastos_filled
FROM tb_solicitudes;
